### ISSUE TITLE
Use of config() instead of rw_config() in authlogic_openid 1.0.3 with authlogic >= 2.0.12

### ISSUE THREAD

**Issue by vazqujav** [binarylogic/authlogic_openid#1]
Authlogic-Changelog for 2.0.12 released 2009-5-13 reads:
Changed config() convenience method to rw_config() to be more descriptive and less vague.

...but methods 'required_fields' and 'optional_fields' in 'lib/authlogic_openid/acts_as_authentic.rb' still use config().

This results in a NoMethodError for people using authlogic-openid in combination with authlogic >= 2.0.12.

**Comment by anotherjesse** [comment]
arg!!!!  I just figured this out after fighting with the example :(  I should have read the issues first

**Comment by adamsalter** [comment]
Same.
Please fix.

**Comment by ghost** [comment]
I release an update with this fix. Thanks.
