### ISSUE TITLE
authlogic_openid github gem

### ISSUE THREAD

**Issue by adamsalter** [binarylogic/authlogic_openid#2]
Can you make this available as a gem from github?

**Comment by ghost** [comment]
Yeah, just curious, any reason why?

**Comment by adamsalter** [comment]
I actually was looking for this as a gem with the update/fix from the previous issue.
I figured that github would have the fix before the rubyforge version.... as it stands neither has that fix ;)
it's probably not a big issue, but I use github over rubyforge if I want to really stay current.

**Comment by graaff** [comment]
It looks like the 1.0.4 release never made it to rubyforge. rubyforge still reports authlogic-oid-1.0.3 as the latest version, e.g. using "gem list --remote authlogic-oid"

**Comment by ghost** [comment]
This should be on rubyforge now. Thanks!
